### ISSUE TITLE
Feature Request - Exclude folders based on CSV

### ISSUE THREAD

**Issue by bobsa31** [codaamok/Get-CMUnusedSources#16]
Hi,

I love this script, however, it would be great if it could exclude folders based on an exclusions CSV. Would this be possible?

Thanks
Bobby

**Comment by codaamok** [comment]
Hello!

I agree, it is missing this. It is something I wanted to implement a while ago, I got a little note in a comment of the code at https://github.com/codaamok/Get-CMUnusedSources/blob/master/Get-CMUnusedSources.ps1#L159 😄 

I will add it to the list, thanks for the suggestion!

**Comment by codaamok** [comment]
Still requires documentation update and support added in to `Start-AltFolderSearch` function, what I have is currently in the [develop](https://github.com/codaamok/Get-CMUnusedSources/tree/develop) branch. Going to finish up the rest to eventually put it in master.

**Comment by codaamok** [comment]
All good, `-ExcludeFolders` now merged in to `master` branch. Docs have been updated to reflect on how to use.

As for your specify request to exclude based on .csv, you'll have to import first to create an array and then pass the array to `-ExcludeFolders`. It felt like the most comfortable way to fulfil the idea and not limit it to just .csv.

It would be something like:

```powershell
$ExcludedFolders = Import-Csv -Path .\folders.csv
$result = .\Get-CMUnusedSources.ps1 -SourcesLocation "\\server\folder$" -SiteServer "server.contoso.com" -ExcludeFolders $ExcludedFolders.Folders
```

... assuming your .csv has a header in the first row named `Folders`.
