### ISSUE TITLE
HTML Report generation send a warning

### ISSUE THREAD

**Issue by Tuttu** [codaamok/Get-CMUnusedSources#3]
When using the `-HTMLReport` switch to generate an HTML report, the script generates a warning.
Note that I wasn't able to reproduce it constantly. 

```Table Header can't be processed properly. Names on the list to merge were not found in Table Header```

**Comment by ChrisKibble** [comment]
@Tuttu - can you check the version of PSWriteHTML you're using just so I can try and repo (along with (@codaamok I'm sure)?

```
Get-Module PSWriteHTML
$(Get-Module PSWriteHTML).Version.ToString()
```

**Comment by Tuttu** [comment]
Woops, I forgot to add the version.
I'm using the latest version, 0.0.45. :)

**Comment by codaamok** [comment]
Is this still an issue with the latest code?

**Comment by Tuttu** [comment]
I didn't got the warning with the dev version. I must have got it when using the older version of PSWriteHtml.

**Comment by codaamok** [comment]
I'm pretty sure you mentioned in Slack you saw this again?

```
Content objects: 2531
Folders at \\server\sources$\Installs\Versions Windows 10\9-Correctif: 155
Folders where access denied: 0
Folders unused: 0
Disk space in "\\server\sources$\Installs\Versions Windows 10\9-Correctif" not used by ConfigMgr content objects (Package, Application, Driver, DriverPackage, OperatingSystemImage, OperatingSystemInstaller, BootImage, SoftwareUpdateDeploymentPackage):  MB
```

**Comment by Tuttu** [comment]
Yep. I updated the corresponding issue. :)
https://github.com/codaamok/Get-CMUnusedSources/issues/4#issuecomment-513696717

**Comment by codaamok** [comment]
Doh, wrong issue. Still new at this, sorry!
