### ISSUE TITLE
Error with multiple versions of PSWriteHTML Installed

### ISSUE THREAD

**Issue by ChrisKibble** [codaamok/Get-CMUnusedSources#7]
There are multiple errors thrown when doing the version check on PSWriteHTML if there is more than one version installed.  Should be easily fixed by either checking all of them against the needed version, or failing if there is more than one version.  I'm honestly not sure how PowerShell handles side-by-side installations of modules, if we can't guarantee it'll use the latest, you should probably fail on multiple installs where any one of them is below your required version.

**Comment by codaamok** [comment]
I just tested this installing versions 0.0.39 - 0.0.45 and I didn't get any errors, not to console or log.

I even tried importing multiple versions to my session before running the script and I experienced no issues.

Are you able to copy/paste the errors you get please?

**Comment by ChrisKibble** [comment]
I think it was in develop I saw the issues. If you still have both installed can you test there?

**Comment by codaamok** [comment]
I was originally trying on develop but I just switched to master and I do see the issue there. It's because the develop branch does not include your PRs from last week :-) working on it!

**Comment by codaamok** [comment]
Thanks @ChrisKibble nice catch. Solution was relatively simple: set `-MinimumVersion` when using `Import-Module` then get all modules for PSWriteHtml that are loaded, grab latest and then check if that's minimum `0.0.44` :-)
