### ISSUE TITLE
The & operator is reserved for future use

### ISSUE THREAD

**Issue by daCritic** [codaamok/Get-CMUnusedSources#9]
Seeing this when running the command.
Thanks.

At C:\Temp\Get-CMUnusedSources.ps1:143 char:19
+               Sign&nbsp;up
+                   ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Temp\Get-CMUnusedSources.ps1:170 char:190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Temp\Get-CMUnusedSources.ps1:170 char:261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Temp\Get-CMUnusedSources.ps1:184 char:255
+ ... ogged out) Header, go to Customer stories">Customer stories <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Temp\Get-CMUnusedSources.ps1:184 char:326
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Temp\Get-CMUnusedSources.ps1:185 char:231
+ ... ata-ga-click="(Logged out) Header, go to Security">Security <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Temp\Get-CMUnusedSources.ps1:185 char:302
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Temp\Get-CMUnusedSources.ps1:205 char:222
+ ... a-click="(Logged out) Header, go to Explore">Explore GitHub <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Temp\Get-CMUnusedSources.ps1:205 char:293
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Temp\Get-CMUnusedSources.ps1:208 char:107
+ ...  text-normal text-mono f5 mb-2 border-lg-top pt-lg-3">Learn &amp; con ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

**Comment by codaamok** [comment]
Sounds like a dodgy copy and paste or download. Either clone the repo or copy while viewing the script in "raw" format.

Create the .ps1 file and execute that. Hopefully the examples in the README are clear enough.

**Comment by daCritic** [comment]
Yes I think the C&P was the problems. Examples are great. Thanks.
